CREATE TABLE noteful_folder(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_name TEXT NOT NULL,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE noteful_notes
    ADD COLUMN 
        folder_id INTEGER REFERENCES noteful_folder(id)
        ON DELETE SET NULL;